
export const BASE_URL=process.env.REACT_APP_BACKEND_API
export const REACT_APP_CLOUDINARY_CLOUD_NAME  =
  process.env.REACT_APP_CLOUDINARY_CLOUD_NAME;
export const REACT_APP_CLOUDINARY_UPLOAD_PRESET =
  process.env.REACT_APP_CLOUDINARY_UPLOAD_PRESET;
  export const COMMENT_PER_POST=2;
  export const POSTS_PER_PAGE=2;
  export const POSTLIST_PER_PAGE=9;
  export const API_GOOGLE_KEY=
  process.env.REACT_APP_API_GOOGLE_KEY;
